services:
  mysql:
    image: mysql:8.4
    container_name: mysql-instance
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_despesas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  app:
    build: .
    ports: [ "8080:8080" ]
    depends_on: [ "mysql" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sistema_despesas?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-net

volumes:
  mysql_data:

networks:
  app-net:
